=== daisytown/reference/DB/Oracle/ORACLE新体系/第14天/JAVAXML/new/student.xsd
<?xml version="1.0" encoding="gb2312"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="roster" type="rosterType"/>
	<xs:complexType name="rosterType">
		<xs:sequence>
			<xs:element name="student" type="studentType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="studentType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="sex" type="sexType"/>
			<xs:element name="birthday" type="xs:date"/>
			<xs:element name="score" type="scoreType"/>
			<xs:element name="skill" type="xs:string" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="ID" type="xs:string"/>
	</xs:complexType>
	<xs:simpleType name="sexType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ÄÐ"/>
			<xs:enumeration value="Å®"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="scoreType">
		<xs:restriction base="xs:positiveInteger">
			<xs:maxExclusive value="100"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== daisytown/reference/DB/Oracle/ORACLE新体系/第14天/JAVAXML/new/student_schema.xml
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="student.xsl"?><roster xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="student.xsd">	<student ID="101">		<name>李华</name>		<sex>男</sex>		<birthday>1978-09-12</birthday>		<score>92</score>		<skill>Java</skill>		<skill>Oracle</skill>		<skill>C Sharp</skill>		<skill>SQL Server</skill>	</student>	<student ID="102">		<name>倪冰</name>		<sex>女</sex>		<birthday>1978-09-12</birthday>		<score>89</score>		<skill>Visual Basic</skill>		<skill>SQL Server</skill>		<skill>ASP</skill>	</student>	<student ID="103">		<name>张君宝</name>		<sex>男</sex>		<birthday>1978-09-12</birthday>		<score>98</score>		<skill>C Sharp</skill>		<skill>SQL Server</skill>		<skill>UML</skill>	</student>	<student ID="104">		<name>杨惠</name>		<sex>女</sex>		<birthday>1978-09-12</birthday>		<score>85</score>		<skill>Visual C++</skill>		<skill>SQL Server</skill>		<skill>UML</skill>	</student>	<student ID="105">		<name>崔春晓</name>		<sex>男</sex>		<birthday>1978-09-12</birthday>		<score>86</score>		<skill>UML</skill>		<skill>C Sharp</skill>		<skill>XML</skill>		<skill>SQL Server</skill>	</student></roster>
