=== daisytown/reference/DB/Oracle/oracle 资料/ORACLE新体系/第14天/JAVAXML/new/Ch12-4.dtd
<?xml version="1.0" encoding="GB2312"?>
<!ELEMENT booklist (book+)>
<!ELEMENT book (code, title, authorlist, price)>
<!ATTLIST book
    sales (N | Y) #REQUIRED
>
<!ELEMENT code (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT authorlist (author+)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT price (#PCDATA)>

=== daisytown/reference/DB/Oracle/oracle 资料/ORACLE新体系/第14天/JAVAXML/new/Ch12-4.xml
<?xml version="1.0" encoding="GB2312"?>
<!--网页制作彻底研究系列-->
<!DOCTYPE booklist SYSTEM "Ch12-4.dtd">
<booklist>
   <book sales="N">
      <code>F8915</code>
      <title>ASP网页制作彻底研究</title>
      <authorlist> 
         <author>陈会安</author>
      </authorlist>
      <price>580</price>
   </book>
   <book sales="Y">
      <code>F8916</code>
      <title>ASP与IIS 4/5网站架设彻底研究</title>
      <authorlist>
         <author>陈会安</author>
      </authorlist>
      <price>550</price>
   </book>
   <book sales="Y">
      <code>F8421A</code>
      <title>Windows 98第二版区域网路筑巢专案</title>
      <authorlist>
         <author>陈会安</author>
      </authorlist>
      <price>480</price>
   </book>
</booklist>
