=== daisytown/reference/DB/Oracle/oracle 资料/ORACLE新体系/第14天/JAVAXML/new/student.dtd
<?xml version="1.0" encoding="UTF-8"?><!ELEMENT roster (student+)><!ELEMENT student (name, sex, birthday, score, skill+)><!ELEMENT name (#PCDATA)><!ELEMENT sex (#PCDATA)><!ELEMENT birthday (#PCDATA)><!ELEMENT score (#PCDATA)><!ELEMENT skill (#PCDATA)><!ATTLIST student	ID CDATA #REQUIRED>

=== daisytown/reference/DB/Oracle/oracle 资料/ORACLE新体系/第14天/JAVAXML/new/student_dtd.xml
<?xml version="1.0" encoding="gb2312"?>
<!-- edited with XML Spy v4.2 U (http://www.xmlspy.com) by hcy (accp) -->
<?xml-stylesheet type="text/xsl" href="student.xsl"?>
<!DOCTYPE roster SYSTEM "student.dtd">
<roster>
	<student ID="101">
		<name>Àî»ª</name>
		<sex>ÄÐ</sex>
		<birthday>1978.9.12</birthday>
		<score>92</score>
		<skill>Java</skill>
		<skill>Oracle</skill>
		<skill>C Sharp</skill>
		<skill>SQL Server</skill>
	</student>
	<student ID="102">
		<name>Äß±ù</name>
		<sex>Å®</sex>
		<birthday>1979.1.12</birthday>
		<score>89</score>
		<skill>Visual Basic</skill>
		<skill>SQL Server</skill>
		<skill>ASP</skill>
	</student>
	<student ID="103">
		<name>ÕÅ¾ý±¦</name>
		<sex>ÄÐ</sex>
		<birthday>1982.9.9</birthday>
		<score>98</score>
		<skill>C Sharp</skill>
		<skill>SQL Server</skill>
		<skill>UML</skill>
	</student>
	<student ID="104">
		<name>Ñî»Ý</name>
		<sex>Å®</sex>
		<birthday>1980.5.16</birthday>
		<score>85</score>
		<skill>Visual C++</skill>
		<skill>SQL Server</skill>
		<skill>UML</skill>
	</student>
	<student ID="105">
		<name>´Þ´ºÏþ</name>
		<sex>ÄÐ</sex>
		<birthday>1981.4.19</birthday>
		<score>86</score>
		<skill>UML</skill>
		<skill>C Sharp</skill>
		<skill>XML</skill>
		<skill>SQL Server</skill>
	</student>
</roster>
