=== daisytown/reference/DB/Oracle/oracle 资料/ORACLE新体系/第13天/XML专有名词.dtd
<?xml version="1.0" encoding="UTF-8"?><!--DTD generated by XMLSPY v2004 rel. 3 U (http://www.xmlspy.com)--><!ELEMENT definition (#PCDATA | title)*><!ELEMENT glossary (item+)><!ELEMENT item (title, definition)><!ELEMENT title (#PCDATA)><!ATTLIST title	version CDATA #IMPLIED>

=== daisytown/reference/DB/Oracle/ORACLE新体系/第13天/XML专有名词.xml
<?xml version="1.0" encoding="GB2312"?><!DOCTYPE glossary SYSTEM "XML专有名词.dtd"><glossary>	<item>		<title version="EN">eXtensible Markup Language</title>		<definition>可扩展标记语言<title>XML</title>		</definition>	</item>	<item>		<title version="EN">encoding</title>		<definition>字符集</definition>	</item>	<item>		<title version="EN">Uniform Resource Identifier</title>		<definition>统一数据标记符号<title>URI</title>		</definition>	</item></glossary>
